language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  # install python 3.6.7
install:
  - pip install numpy, scipy
  - pip install -i https://test.pypi.org/simple/ SICER

script: pytest
