os:
  - linux
  - osx
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  # install python 3.6.7
install:
  - pip install numpy
  - pip install scipy
  - pip install -i https://test.pypi.org/simple/ SICER


script:
  - bash ./test/travisCI/test.sh
