site_name: SICER2 Documentation
pages:
    - 'Quick Start': index.md
    - 'Workflow of SICER2': workflow.md
    - 'Understanding SICER2 Outputs': sicer2_output.md
    - Contact: contact.md
theme: readthedocs
repo_url: https://github.com/jeffreyyoo/SICER-2
site_author: Jin Yong Yoo
